export const CategoriesLists = [
    "All communities",
    "Sports",
    "Gaming",
    "News",
    "TV",
    "Aww",
    "Memes",
    "pics & Gifs",
    "Travel",
    "Tech",
    "Music",
    "Art",
    "Beauty",
    "Books & Writing",
    "Crypto",
    "Discussion",
    "E3",
    "Fashion",
    "Finance & Business",
    "Food",
    "Health & Fitness",
    "Learning",
    "Mindblowing",
    "Outdoors",
    "Parenting",
    "Photography",
    "Relationships",
    "Science",
    "Videos",
    "Technology",
    "Music",
    "Animals",
    "Hystory"
]